version: '3'

volumes:
  sqlite3:

services:
  app:
    build: ./
    container_name: fastapi_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - sqlite3:/app/fastapi_app/database/
